### PR TITLE
Flakes Integration

### LINKED ISSUE #1: Setup flake.nix to provide integration into Nix's flake system
This repository should have a public `flake.nix` so it can work seamlessly for downstream users.

Documentation is necessary in the `README.md` that explains how to make use of this, and how to integrate this into downstream repositories like all of our `js-*` libraries.

It can also be integrated into people's `config.nix` so that way one may use `nix-env` or similar commands. Documentation should be done here.

### Tasks

- [x] 1. Create a `flake.nix`
- [x] 2. Change structure of the repository for proper extension points
- [x] 3. Document the extension points
- [x] 4. Document how users are supposed to integrate this into their development repositories, their user environment and so-on.

### PR DESCRIPTION
**Pull request by brynblack**
### Description

This pull request adds Flake support to the overlay, so that people can integrate Flakes into their pre-existing projects or deployments. It will replace the legacy deployment system using overlay.nix, and will only be compatible with flake-only configurations.

### Issues Fixed

* Fixes #1 

### Tasks

- [x] 1. Add flake configuration
- [x] 2. Update documentation

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by brynblack** [comment]
I think this can be merged now.

**Comment by CMCDragonkai** [comment]
Update title of PR and also being squashing too.

**Comment by brynblack** [comment]
Squashed and rebased, everything works, ready for merge.

**Comment by CMCDragonkai** [comment]
Tick the sanity check if so.

**Pull request merged**
